apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus       # UID tetap agar dashboard JSON bisa reference langsung
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    orgId: 1
    editable: true
